### PR TITLE
del user and role after disable auth

### PR DESCRIPTION
**Pull request by stonelion**
After disable auth,use the non-auth client connection to delete test user and role.

### CODE REVIEW

**Comment by fanminshi** [comment]
@stonelion have you manually test this change?

**Comment by heyitsanthony** [comment]
This test wasn't failing in CI (see https://travis-ci.org/coreos/jetcd/builds/231622081) -- is CI broken or is the test OK as-is?

Why did the file permissions change from 644 to 755?

**Comment by stonelion** [comment]
@heyitsanthony windows change the file permissions automatically??

**Comment by stonelion** [comment]
@fanminshi yes.

**Comment by xiang90** [comment]
@fanminshi this pr makes sense. can we cheery pick this and get it merged?

or @stonelion can you rebase with master?

**Comment by fanminshi** [comment]
@xiang90 I'll cherry pick the commit.

**Comment by fanminshi** [comment]
close via https://github.com/coreos/jetcd/pull/103

**Comment by stonelion** [comment]
@fanminshi thank you

**Pull request closed without merging**
