### PR TITLE
style: remove prefix etcd* from class name

### PR DESCRIPTION
**Pull request by fanminshi**

### CODE REVIEW

**Comment by xiang90** [comment]
LGTM if CI passes.

**Comment by fanminshi** [comment]
@xiang90 should I have client suffix like WatchClient, KVClient, LeaseClient..? specifically, there is already a class called Lease that just hold lease information. so Lease (client) conflicts with Lease.

**Comment by xiang90** [comment]
probably rename https://github.com/coreos/jetcd/blob/master/src/main/java/com/coreos/jetcd/lease/Lease.java this thing.

**Comment by fanminshi** [comment]
yeah, it seems to me that's same as `keepAlive` in go client. so i'll change it to that.

**Pull request merged**
