### PR TITLE
post_release: bump version to 0.1.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by fanminshi**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Usually setting up the next snapshot version is done by the release plugin

**Comment by fanminshi** [comment]
@lburgazzoli that's a good idea. I'll try to get the plugin working for the next release.

**Comment by lburgazzoli** [comment]
lgtm

**Comment by vorburger** [comment]
+1 this seems like a good idea - seeing a 0.0.1 non-SNAPSHOT on a master branch was the very first thing that struck me as being unusual when I started to look through the sources of this project...

Given that https://github.com/coreos/jetcd/issues/193 is done now (see https://search.maven.org/#search%7Cga%7C1%7Ccoreos), could this happen now? It's trivial so I don't suppose I can help in any way, but if you do need help, please let me know how one may contribute to get this merged (conflicts need to be resolved, but I won't be able to amend this PR - can raise another one, if you like).

**Comment by fanminshi** [comment]
@vorburger i'll get this merge today.

**Pull request merged**
