### PR TITLE
ErrorCode: credit google for ErrorCode.java

### PR DESCRIPTION
**Pull request by fanminshi**

### CODE REVIEW

**Comment by xiang90** [comment]
is the original code also apache2?

**Comment by fanminshi** [comment]
@xiang90 yes.

**Comment by fanminshi** [comment]
@xiang90 https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/ErrorCode.java

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
