### PR TITLE
fix get methods access issue

### PR DESCRIPTION
**Pull request by AdoHe**
those getter methods should be `public`.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@AdoHe 

Why all the new*Client have been made private ? 

In addition I would make all the get*Client lazy i.e. wi th Suppliers.memorize so the client do not allocate unused objects.

**Comment by bkrahmer** [comment]
I was about to add an issue for the same thing before a colleague spotted this pull request.  Can you please merge it?  thanks!

**Comment by AdoHe** [comment]
@bkrahmer merged, ptal.

**Comment by lburgazzoli** [comment]
@AdoHe so the new* are all private and clients are created inside the contructor ?

**Pull request merged**
