### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by lburgazzoli**
I've opened this PR to clean-up a little the code in the following area:

- stubs are not more created inside the client but in the specific client so it is up to them to create as many stubs as needed
- clients (and stubs) are lazy created so no memory allocation done unless really needed
- Some functions have been improved to leverage Java8
- I've introduced Optional where it make sense so it is clear when something is well, optional :)

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@AdoHe any chance to get this PR reviewed ?

**Comment by AdoHe** [comment]
@lburgazzoli I am glad to see more clean code, let's get this in.

**Comment by lburgazzoli** [comment]
@AdoHe thx, btw if you need any help please ask, I'd like to integrate jetcd (and etcdv3) in Apache Camel

**Comment by AdoHe** [comment]
@lburgazzoli thanks very much, I would hope we can work together to get this ready asap, the biggest issue is the watch implementation, really appreciate if you could help review PR #45. Once this get merged and all the tests pass, we can push it to the central maven and announce it is ready for use.

**Comment by lburgazzoli** [comment]
I will have a look soon

**Comment by AdoHe** [comment]
@lburgazzoli thanks again. :)

**Pull request merged**
