### PR TITLE
example: add a simple etcdctl example using jetcd client

### PR DESCRIPTION
**Pull request by fanminshi**
add jetcd-simple-ctl example to illustrate how to build a simple ctl of GET, PUT, and WATCH using jetcd client.

### CODE REVIEW

**Comment by fanminshi** [comment]
PTAL cc/ @lburgazzoli

**Comment by lburgazzoli** [comment]
not sure jetcd-examples/jetcd-simple-ctl/mvnw  is needed

**Comment by fanminshi** [comment]
@lburgazzoli with mvnw, it makes the README examples easier to follow or else i'll assume the the user to have `mvn` installed.

**Comment by lburgazzoli** [comment]
So you need mvnw.bat too ;)

**Comment by fanminshi** [comment]
@lburgazzoli true. what's do you think it is best way to run the example then?

**Comment by fanminshi** [comment]
@lburgazzoli added support for windows

**Pull request merged**
