### PR TITLE
Provide a more friendly transaction builder

### PR DESCRIPTION
**Pull request by emiapwil**
Regarding this issue: https://github.com/coreos/jetcd/issues/60

Signed-off-by: Emiapwil (Gao Kai) <emiapwil@gmail.com>

### CODE REVIEW

**Comment by heyitsanthony** [comment]
should this include a test so the functionality isn't unintentionally clobbered in the future?

**Comment by xiang90** [comment]
this change allows things like:

if(x).if(x).then(x).if(x).then(x), which does not make any sense.

for each builder, we should allow exact one if, else, then. we should throw exception otherwise.

**Comment by emiapwil** [comment]
Point taken. I will do that in a few days.

**Comment by fanminshi** [comment]
@emiapwil could address @xiang90's concern and add few tests for this?

**Comment by fanminshi** [comment]
close this via https://github.com/coreos/jetcd/pull/101

**Pull request closed without merging**
