### PR TITLE
add abstract etcd name resolver

### PR DESCRIPTION
**Pull request by AdoHe**
@lburgazzoli I just add `AbstractEtcdNameResolver` ptal. If any problem, we can discuss.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
I'm unsure about the multiple uri provided as constructor arg as [NameResolver.Factory::newNameResolver](http://www.grpc.io/grpc-java/javadoc/io/grpc/NameResolver.Factory.html#newNameResolver-java.net.URI-io.grpc.Attributes-) expects a single uri, am I wrong?

**Comment by AdoHe** [comment]
Yes, `newNameResolver` expects a single target uri, which name resolver will resolve this target uri to specific addresses, I think in our case, the target uri would be: `dns+srv://_etcd-server._tcp.example.com` for dns based name resolver, and `etcd://etcd.v3.cluster` for simple name resolver.

**Comment by lburgazzoli** [comment]
So I guess we should remove the multiple uri pram, isn't it ?

**Comment by AdoHe** [comment]
Actually the reason I put multiple uri param here is users have to provide specific endpoints addresses when they use simple name resolver. For dns based name resolver, this info can be resolved through dns SRV records, for simple name resolver, this info must be configured manually.

**Comment by AdoHe** [comment]
Maybe not a very good usage, if you have better suggestion, we can change this.

**Comment by lburgazzoli** [comment]
I see the reason but I think abstract classes should stick to the interface contract/expected behavior, then simple resolver is free to change it.

**Comment by AdoHe** [comment]
Yes, this sounds more reasonable, I will change in when I am near computer.

**Comment by lburgazzoli** [comment]
Would it make sense, in the future, to contribute AbstractEtcdNameResolver and dns-srv discovery to o grpc-java ?

**Comment by AdoHe** [comment]
@lburgazzoli I am not sure about this, maybe you can open an issue on grpc-java repo.

**Comment by AdoHe** [comment]
@lburgazzoli I just update this, ptal. I am going to merge it if everything ok, thus you can reuse it.

**Comment by lburgazzoli** [comment]
Fine with me, we can change it later on if needed

**Comment by AdoHe** [comment]
@lburgazzoli I just merged this, please update PR #25

**Comment by lburgazzoli** [comment]
@AdoHe done

**Pull request merged**
