### PR TITLE
add the init maven project and generated code

### PR DESCRIPTION
**Pull request by AdoHe**
@xiang90 I just noticed this project, and I think it's a better place to implement etcd v3 java client even though I add some init commits on my own repo. In this pr, I just add the init maven project and generated code, I think next I will implement the specific service client.

### CODE REVIEW

**Comment by skyao** [comment]
Hello, Adohe, why you commit the generated java code to git? We need't do this, there are so many files.

**Comment by skyao** [comment]
I pulled another request like you, but no generated java files committed.

And for the grpc version, I suggest to use the latest version 0.15.0.

**Comment by xiang90** [comment]
Let's do not check in the generate code for now. I will merge in @skyao initial proto setup.

**Comment by AdoHe** [comment]
That's ok.

**Pull request closed without merging**
